# This is a basic workflow to help you get started with Actions
name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch -n <github> --auth-mode key -d <cgVxK+EZI/JdglKJNCCe4aq+tYlbDAiBfODbcndbID2DxjKzS7Ry51aBfKeLXYNkKfvVL/rV2Sai6/bSEW2Zig==> -s .
